---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-to-logzio
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-to-logzio
  namespace: monitoring
rules:
- apiGroups:
  - "aquasecurity.github.io"
  - ""
  - apps
  resources:
  - namespaces
  - vulnerabilityreports
  - pods
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trivy-to-logzio
roleRef:
  kind: ClusterRole
  name: trivy-to-logzio
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: trivy-to-logzio
  namespace: monitoring
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-to-logzio
  namespace: monitoring
  labels:
    k8s-app: trivy-to-logzio
    version: v1
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: trivy-to-logzio
            version: v1
        spec:
          serviceAccount: trivy-to-logzio
          serviceAccountName: trivy-to-logzio
          restartPolicy: OnFailure
          containers:
          - name: trivy-to-logzio
            image: logzio/trivy-to-logzio:latest
            imagePullPolicy: Always
            env:
            - name: LOGZIO_LOG_SHIPPING_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logzio-logs-secret
                  key: logzio-log-shipping-token
            - name: LOGZIO_LOG_LISTENER
              valueFrom:
                secretKeyRef:
                  name: logzio-logs-secret
                  key: logzio-log-listener
            - name: ENV_ID
              value: 'my_env_id'
          terminationGracePeriodSeconds: 30

